#!/usr/bin/env node
/**
 * Renders every fixed-size form of the Orbit mark from one set of numbers.
 *
 *   npm run icons
 *
 * Outputs (all committed, so a fresh clone needs no toolchain to build):
 *   public/orbit.svg            favicon, also the <link rel=icon> source
 *   public/icons/icon-192.png   PWA
 *   public/icons/icon-512.png   PWA
 *
 * The geometry lives in src/components/shell/orbit-geometry.json, which the
 * React component reads too — that file is the only place the shape is
 * described, so the topbar and the favicon cannot drift apart.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import sharp from "sharp"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const geometryPath = resolve(root, "src/components/shell/orbit-geometry.json")
const geometry = JSON.parse(await readFile(geometryPath, "utf8"))

const { viewBox, ellipse, dot, brand, background, iconScale } = geometry

/**
 * The legibility invariant, checked rather than commented.
 *
 * At favicon size the ring and the dot are only a pixel or two apart, so the
 * ring's inner edge has to clear the dot's radius outright — when it does not,
 * the two merge into an orange blob and the mark stops reading as an orbit.
 * This has already happened once; the check is here so it cannot happen again
 * quietly.
 */
const innerEdge = ellipse.ry - ellipse.strokeWidth / 2
const gap = innerEdge - dot.r
const minGap = 1.2
if (gap < minGap) {
  console.error(
    `\n✗ Mark tidak akan kebaca di ukuran kecil.\n` +
      `  Tepi dalam cincin (ry ${ellipse.ry} − stroke/2 ${ellipse.strokeWidth / 2} = ${innerEdge.toFixed(2)})\n` +
      `  cuma berjarak ${gap.toFixed(2)} unit dari titik (r ${dot.r}); minimal ${minGap}.\n` +
      `  Perbesar ry, tipisin stroke, atau kecilin titiknya.\n`,
  )
  process.exit(1)
}

/** The two shapes, at whatever colour and scale the caller needs. */
function shapes(color) {
  return (
    `<ellipse cx="${ellipse.cx}" cy="${ellipse.cy}" rx="${ellipse.rx}" ry="${ellipse.ry}" ` +
    `stroke="${color}" stroke-width="${ellipse.strokeWidth}" fill="none" ` +
    `transform="rotate(${ellipse.rotate} ${ellipse.cx} ${ellipse.cy})"/>` +
    `<circle cx="${dot.cx}" cy="${dot.cy}" r="${dot.r}" fill="${color}"/>`
  )
}

// ── favicon ────────────────────────────────────────────────────────────────
// Transparent background: the tab strip supplies its own, light or dark.
const faviconSvg =
  `<svg viewBox="0 0 ${viewBox} ${viewBox}" fill="none" xmlns="http://www.w3.org/2000/svg">\n` +
  `  <!-- GENERATED by scripts/generate-icons.mjs — edit orbit-geometry.json instead. -->\n` +
  `  ${shapes(brand)}\n` +
  `</svg>\n`

await writeFile(resolve(root, "public/orbit.svg"), faviconSvg)
console.log("  public/orbit.svg")

// ── PWA icons ──────────────────────────────────────────────────────────────
// Declared "any maskable" in the manifest, so a launcher may crop these to a
// circle or squircle. A full-bleed background plus a mark at iconScale keeps
// everything that matters inside the safe zone.
const offset = ((1 - iconScale) / 2) * viewBox
const iconSvg =
  `<svg viewBox="0 0 ${viewBox} ${viewBox}" xmlns="http://www.w3.org/2000/svg">` +
  `<rect width="${viewBox}" height="${viewBox}" fill="${background}"/>` +
  `<g transform="translate(${offset} ${offset}) scale(${iconScale})">${shapes(brand)}</g>` +
  `</svg>`

await mkdir(resolve(root, "public/icons"), { recursive: true })
for (const size of [192, 512]) {
  const out = resolve(root, `public/icons/icon-${size}.png`)
  await sharp(Buffer.from(iconSvg), { density: 384 })
    .resize(size, size)
    .png({ compressionLevel: 9 })
    .toFile(out)
  console.log(`  public/icons/icon-${size}.png`)
}

console.log(`\n✓ Selesai — celah cincin ke titik ${gap.toFixed(2)} unit (min ${minGap}).`)
